on:
  push:
    branches:
      - master
jobs:
  preview:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with: 
          persist-credentials: false
          
      - name: 安装依赖
      - run: npm install
      
      - name: 构建
      - run: npm run build
      
      - name: 部署
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: preview
          FOLDER: /dist
